name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chocolatey (Windows package manager)
        if: runner.os == 'Windows'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Arduino CLI (Windows)
        if: runner.os == 'Windows'
        run: choco install arduino-cli -y

      - name: AVR Core Installation
        run: arduino-cli.exe core install arduino:avr

      - name: Planet096 Example Dependencies
        run: |
          git clone https://github.com/adafruit/Adafruit_SSD1306.git
          git clone https://github.com/adafruit/Adafruit-GFX-Library.git
          git clone https://github.com/adafruit/Adafruit_BusIO.git

      - name: Build Arduino library
        run: |
          arduino-cli compile --fqbn arduino:avr:mega --library src --library Adafruit-GFX-Library --library Adafruit_BusIO --library Adafruit_SSD1306 --build-path build examples/full_example/full_example.ino
